test('First test', () => { throw new Error('fail') })